### ISSUE TITLE
{ if modules.xx } no longer works

### ISSUE THREAD

**Issue by thoraxe** [osevg/workshopper#11]
In the old Ruby app we had the following:

```ruby
{% if modules.pipelines %}
```

This doesn't appear to work in the Java version. Therefore the current codechanges and pipelines labs are broken as these don't evaluate correctly.

@marekjelen can you please fix this super quickly? or maybe @jorgemoralespou or @siamaksade 

Kinda urgent.

**Comment by marekjelen** [comment]
Fixed by a17598eb29ac6a7902630845c6c35b7454d12959
