### ISSUE TITLE
Add in context module list

### ISSUE THREAD

**Issue by jorgemoralespou** [osevg/workshopper#14]
Have a list on the module with the list of modules, those that are done, those that are missing, that is navigable.

Example:
https://kiosk-dot-codelabs-site.appspot.com/codelabs/cloud-shell/index.html?index=..%2F..%2Fdevoxx#1

![image](https://cloud.githubusercontent.com/assets/78350/23763464/0464bedc-04fa-11e7-997d-6556ae40bd1b.png)

**Comment by marekjelen** [comment]
Their approach is slightly different then ours. The kiosk is design for multiple workshops in single deployment, rather then ours where we mostly work with single workshop in single deployment.

Our structure is

Workshop list (often hidden) -> Module list -> Module content

Their structure is

Workshop list -> Module content (with module list in the view, as on the picture)

I am not sure if this makes sense for us. Can you add your views, please.

//cc @thoraxe @siamaksade @gshipley @GrahamDumpleton @thesteve0

**Comment by jorgemoralespou** [comment]
In my view, when we use single workshop, I would just directly go to this page. Not module list, since I would embed the module list in the left.

**Comment by marekjelen** [comment]
Prototyped on the "module-list" branch

**Comment by marekjelen** [comment]
Has been merged into master branch.
