### ISSUE TITLE
Resize images so that don't go beyond limits

### ISSUE THREAD

**Issue by jorgemoralespou** [osevg/workshopper#19]
In some examples, the images overflow the space reserved for the content of the module.

Example:
![image](https://cloud.githubusercontent.com/assets/78350/23763856/97912a1e-04fb-11e7-8efd-b54443a2ab64.png)

**Comment by marekjelen** [comment]
Are you using the hosted version? This happens when the custom.css does not get loaded.

**Comment by jorgemoralespou** [comment]
yes
