### ISSUE TITLE
Consolidate env vars for content

### ISSUE THREAD

**Issue by siamaksade** [osevg/workshopper#3]
Is there a need to keep all the three content env vars? 
* `CONTENT_URL_PREFIX`
* `GITHUB_REPOSITORY`
* `GITHUB_REF`

`CONTENT_URL_PREFIX` essential satisfies the requirement for pulling content from other repositories.

**Comment by siamaksade** [comment]
@marekjelen

**Comment by marekjelen** [comment]
The GITHUB_* are there to simplify the construction of CONTENT_URL_PREFIX for github users as it is not the github repo url but link to raw data on the CDN.

**Comment by marekjelen** [comment]
@siamaksade can we close this?

**Comment by siamaksade** [comment]
+1

**Comment by marekjelen** [comment]
thanks
