### ISSUE TITLE
Shorten the workshop ids

### ISSUE THREAD

**Issue by siamaksade** [osevg/workshopper#6]
The workshop ids in the URL are very long and would be more aesthetic to shorten them
/#/workshop/8df65d89543986560ad211a6b0987ee2b3c07e523e204acd227fb0485fd95802

**Comment by marekjelen** [comment]
The system allows to specify the ids in the workshop yaml definition

```yaml
name: Roadshow
id: roadshow
```

**Comment by marekjelen** [comment]
clolsing for the time being, in case the SHA is too long, we can come up with some other way
